# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desafio.Ioasys' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire', '~> 5.2'
  pod 'KeychainSwift', '~> 19.0'

  # Pods for Desafio.Ioasys

  target 'Desafio.IoasysTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Desafio.IoasysUITests' do
    # Pods for testing
  end

end
